In [1]:
import numpy as np

In [3]:
array = np.array([[1, 2, 3],[4, 5, 6]]) 
print(array)

[[1 2 3]
 [4 5 6]]


In [6]:
print('number of dim:',array.ndim) # 维度
print('shape:',array.shape)        # 形状（行数， 列数）
print('size:',array.size)          # 大小 行*列

number of dim: 2
shape: (2, 3)
size: 6


In [9]:
a = np.array([2, 3, 4], dtype = np.int64)
b = np.array([2, 3, 4], dtype = np.float64)
print(a.dtype)
print(b.dtype)

int64
float64


In [20]:
a = np.zeros((3,4)) # 三行四列的零矩阵
print(a)
b = np.ones((3,4)) # 三行四列的单位矩阵
print(b)
c = np.empty((3,4)) # 三行四列的空矩阵
print(c)
a = np.arange(12).reshape((3,4)) # 重新生成数列 
print(a)
d = np.linspace(1,10,5) # 用于生成等间距的数列
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.    3.25  5.5   7.75 10.  ]


In [25]:
a = np.array([10, 20, 30, 40])
b = np.arange(4) # 默认起始0 步长一
#np.arange(起始值, 终止值, 步长) 用于生成等差数列
c = a - b
print(a)   
print(b)                                                                                                                        
print(c)
d = b**2 # 平方
print(d)
e = np.sin(a)
print(e)

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-0.54402111  0.91294525 -0.98803162  0.74511316]


In [30]:
print(b)
print(b < 3)
print(b == 3)

[0 1 2 3]
[ True  True  True False]
[False False False  True]


In [40]:
a = np.array([[1, 1],[0, 1]])
b = np.arange(4).reshape((2, 2))
c = a * b #逐个相乘
c_dot = np.dot(a, b) # 矩阵乘法
c_dot_2 = a.dot(b)
print(c,'\n') 
print(c_dot)
print('\n')
print(c_dot_2)

[[0 1]
 [0 3]] 

[[2 4]
 [2 3]]


[[2 4]
 [2 3]]


In [48]:
a = np.random.random((2, 4))
print(a)
print('总和', np.sum(a))
print('对列求和', np.sum(a, axis = 0)) # 求和 axis = 0列 对列求和
print('最小值', np.min(a)) # 求最小值
print('最大值',np.max(a)) # 求最大值
print('行最大值',np.max(a, axis = 1)) # 求每行最大值

[[0.76491722 0.88432414 0.19018554 0.98125566]
 [0.65902408 0.57221158 0.47065497 0.15295622]]
总和 4.675529404372254
对列求和 [1.42394129 1.45653572 0.66084051 1.13421188]
最小值 0.1529562180254289
最大值 0.981255658755962
行最大值 [0.98125566 0.65902408]


In [49]:
A = np.arange(2, 14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [53]:
print(np.argmin(A)) # 最小值的索引
print(np.argmax(A)) # 最大值的索引

0
11


In [54]:
print(np.mean(A))

7.5


In [63]:
print(np.median(A)) # 中位数

7.5


In [66]:
print(np.cumsum(A)) #累加形式

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [67]:
print(np.diff(A)) #差形式

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [69]:
print(np.nonzero(A)) #输出行索引与列索引

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


In [79]:
A = np.arange(14, 2, -1).reshape((3,4))
print(A,'\n')
print(np.transpose(A),'\n') # 转置
print(A.T,'\n')
print((A.T).dot(A),'\n') # A的转置乘 A （AT*A）
print(np.sort(A)) #轴对称

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]] 

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]] 

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]] 

[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]] 

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [81]:
print(np.clip(A, 5, 9)) # np.clip(array, min, max)裁断 小于5的变5，大于9的变9

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [83]:
print(np.mean(A, axis = 0))
print(np.mean(A, axis = 1))

[10.  9.  8.  7.]
[12.5  8.5  4.5]
