In [1]:
import numpy as np

In [3]:
A = np.arange(3, 15)
print(A)
print(A[3]) # numpy索引

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [8]:
A = np.arange(3, 15).reshape((3,4))
print(A, '\n')
print(A[2]) # 第三行

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]] 

[11 12 13 14]


In [15]:
print(A[0,1])
print(A[1,:])
print(A[:,1])
print(A[:1]) # 切片 =A(0:1) array[start:stop:step]
print(A[1, 1:2]) # 第一行，切片start 1 stop 2

4
[ 7  8  9 10]
[ 4  8 12]
[[3 4 5 6]]
[8]


In [20]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [21]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [29]:
print(A.flatten())
for item in A.flat:
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [56]:
# 拼接
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

print(np.vstack((A,B))) # VERTICAL STACK上下合并

[[1 1 1]
 [2 2 2]]


In [34]:
C = np.vstack((A,B))
print(A.shape, C.shape)

(3,) (2, 3)


In [36]:
D = np.hstack((A, B))  # HORIZONTAL STACKE左右合并
print(D)
print(D.shape)

[1 1 1 2 2 2]
(6,)


In [39]:
print(A[np.newaxis,:])  # 行升维 shape变为（1,3） 
print(A[:,np.newaxis])  # 列升维 shape变为（3,1）

[[1 1 1]]
[[1]
 [1]
 [1]]


In [50]:
A = np.array([1, 1, 1])[:,np.newaxis]
B = np.array([2, 2, 2])[:,np.newaxis]
C = np.concatenate((A, B, B, A), axis = 1) #在第二维度进行拼接
print(C)
D = np.concatenate((A, B, B, A), axis = 0) #在第一维度进行拼接
print(D)

[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]


In [53]:
A = np.array([1, 1, 1])[np.newaxis,:]
B = np.array([2, 2, 2])[np.newaxis,:]
print(A)
print(B)
C = np.concatenate((A, B, B, A), axis = 1) #在第二维度进行拼接 列拼接 左右拼接
print(C)
D = np.concatenate((A, B, B, A), axis = 0) #在第一维度进行拼接 行拼接 上下拼接
print(D)

[[1 1 1]]
[[2 2 2]]
[[1 1 1 2 2 2 2 2 2 1 1 1]]
[[1 1 1]
 [2 2 2]
 [2 2 2]
 [1 1 1]]


In [57]:
#分割
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [62]:
print(np.split(A, 2, axis = 1)) # 列分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [61]:
print(np.split(A, 3, axis = 0)) # 行分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [64]:
print(np.array_split(A, 3, axis = 1)) # 不均匀分割

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [67]:
print(np.vsplit(A, 3)) # 行分割
print(np.hsplit(A, 2)) # 列分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [68]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [69]:
b = a
c = a
d = b
a[0] = 11
a

array([11,  1,  2,  3])

In [71]:
b # 改变了a相当于改变了b

array([11,  1,  2,  3])

In [77]:
b = a.copy() # deep copy深拷贝 只赋值

In [75]:
a[3] = 44
a

array([11,  1,  2, 44])

In [76]:
b

array([11,  1,  2,  3])